CREATE TABLE users(id TEXT PRIMARY KEY,disabled INTEGER NOT NULL DEFAULT 0 CHECK(disabled IN(0,1)),administrator INTEGER NOT NULL DEFAULT 0 CHECK(administrator IN(0,1)),created_at INTEGER NOT NULL DEFAULT(unixepoch()));
CREATE TABLE identities(provider TEXT NOT NULL CHECK(provider IN('email','github','feishu')),namespace TEXT NOT NULL,subject TEXT NOT NULL,user_id TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(provider,namespace,subject));
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at INTEGER NOT NULL);
CREATE INDEX sessions_user ON sessions(user_id);
CREATE TABLE login_challenges(id TEXT PRIMARY KEY,kind TEXT NOT NULL,subject TEXT NOT NULL,secret_hash TEXT NOT NULL,binding_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,consumed INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL DEFAULT(unixepoch()));
CREATE INDEX challenge_limit ON login_challenges(subject,created_at);
CREATE TABLE login_rate(key TEXT PRIMARY KEY,window INTEGER NOT NULL,count INTEGER NOT NULL);
CREATE TABLE device_authorizations(device_hash TEXT PRIMARY KEY,user_code_hash TEXT NOT NULL UNIQUE,name TEXT NOT NULL,user_id TEXT REFERENCES users(id),expires_at INTEGER NOT NULL,consumed INTEGER NOT NULL DEFAULT 0,last_poll INTEGER NOT NULL DEFAULT 0);
CREATE TABLE teams(id TEXT PRIMARY KEY,name TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE memberships(team_id TEXT NOT NULL REFERENCES teams(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN('owner','member')),PRIMARY KEY(team_id,user_id));
CREATE TABLE spaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,team_id TEXT REFERENCES teams(id),user_owner TEXT REFERENCES users(id),epoch TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,archived INTEGER NOT NULL DEFAULT 0,CHECK((team_id IS NULL)!=(user_owner IS NULL)));
CREATE TABLE space_grants(space_id TEXT NOT NULL REFERENCES spaces(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN('viewer','editor','manager')),PRIMARY KEY(space_id,user_id));
CREATE TABLE projects(id TEXT PRIMARY KEY,team_id TEXT NOT NULL REFERENCES teams(id),name TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE project_spaces(project_id TEXT NOT NULL REFERENCES projects(id),space_id TEXT NOT NULL REFERENCES spaces(id),PRIMARY KEY(project_id,space_id));
CREATE TABLE collections(id TEXT PRIMARY KEY,team_id TEXT NOT NULL REFERENCES teams(id),name TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE collection_projects(collection_id TEXT NOT NULL REFERENCES collections(id),project_id TEXT NOT NULL REFERENCES projects(id),PRIMARY KEY(collection_id,project_id));
CREATE TABLE invitations(token_hash TEXT PRIMARY KEY,team_id TEXT NOT NULL REFERENCES teams(id),email TEXT NOT NULL,expires_at INTEGER NOT NULL,consumed_by TEXT REFERENCES users(id));
CREATE TABLE replicas(id TEXT PRIMARY KEY,space_id TEXT NOT NULL REFERENCES spaces(id),user_id TEXT NOT NULL REFERENCES users(id),device TEXT NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,ack_head INTEGER NOT NULL DEFAULT 0,last_seen INTEGER,device_key TEXT NOT NULL,UNIQUE(space_id,user_id,device_key));
CREATE TABLE uploads(id TEXT PRIMARY KEY,space_id TEXT NOT NULL REFERENCES spaces(id),replica_id TEXT NOT NULL REFERENCES replicas(id),user_id TEXT NOT NULL REFERENCES users(id),transfer_json TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('reserved','receiving','uploaded','committed')),created_at INTEGER NOT NULL DEFAULT(unixepoch()),request_key TEXT NOT NULL,UNIQUE(space_id,user_id,request_key));
CREATE TABLE control_audit(id INTEGER PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,created_at INTEGER NOT NULL DEFAULT(unixepoch()));
